version: "3.3"
services:

  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kalen123
      POSTGRES_DB: MyDB

    ports:
      - 5432:5432