server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: PickUpPoint
          uri: http://localhost:8081/
          predicates:
            - Path=/api/orders/**
        - id: EmployeeCustomerService
          uri: http://localhost:8082/
          predicates:
            - Path=/api/customer/**
        - id: WebClient
          uri: http://localhost:8080/
          predicates:
            - Path=/web/**



